### ISSUE TITLE
abandon pkg

### ISSUE THREAD

**Issue by sckott** [ropensci/randgeo#14]
@noamross i'm thinking of abandoning this pkg (& archive on CRAN), any argument to keep it?  i don't see any usage in the wild and I don't use it myself

**Comment by noamross** [comment]
What's the reason _to_ abandon it? Given that it has no Imports, is there a Maintenance impetus for doing so?

There are two public repos using it in some way: https://github.com/search?q=randgeo+language%3AR&type=Code, who knows about private.

**Comment by sckott** [comment]
I'ts become increasingly clear that my attempt at a geojson set of tooling for R isn't being used at all, other than geojsonio, so I've been going through my spatial pkgs and archiving them/etc.  just to remove pkgs that aren't used - no other reason to abandon

**Comment by noamross** [comment]
Huh, that's too bad. I don't have strong opinions about this, though I'd default to abandoning only as maintenance requires it. I'd be curious if the #spatial group and others have opinions as to whether the geojson tools have a place.  But all your call.

**Comment by sckott** [comment]
yeah, i guess it doesn't hurt to leave it as is.  I guess the problem was that I saw geojson being so widely used in the web JS world, and thought it would be popular in R too, but R is not the web :p
