### ISSUE TITLE
add class `geojson_list` to returned value

### ISSUE THREAD

**Issue by timelyportfolio** [ropensci/randgeo#9]
As I started testing some experimental `sfr` geo_json conversion functions (see https://github.com/edzer/sfr/issues/185#issuecomment-284703112), I noticed that `geo_point` and `geo_polygon` return class `list`.  Would it be possible to also class the return values as `geo_list` similar to `geojsonio`?

Thanks so much for this very handy package!

**Comment by sckott** [comment]
thanks for the issue @timelyportfolio 

Yeah, I think so. I'll have a play

**Comment by sckott** [comment]
@timelyportfolio let me know if that does what you need

**Comment by sckott** [comment]
@noamross pinging just in case you haven't any thoughts on this

**Comment by timelyportfolio** [comment]
thanks @sckott, does exactly as expected.  Now, just need to figure out the best mechanism for `sf` auto-conversion of `geo_json` and `geo_list` since `character` and `list` are assumed by `sf` to be something other than `geojson`.
